Us02 main page
WildCodeSchool-2024-02/JS-lyon-0224-P3-wildygamy pull request #10
Opened 2024-06-06 14:28 UTC by MaxAnxxi

Front : Listes des jeux avec en grand le challenge de la semaine
En tête et pied de page
Back : Création de la base de données avec la table jeu 
Lien Back to Front : Routes

Tech : Fetch des données de la BDD vers le front pour avoir un mapping des jeux sur la page principale

2024-06-06 15:03 UTC, Salma-D38 approved these changes
ok

2024-06-06 15:04 UTC, Salma-D38 approved these changes

2024-06-06 15:07 UTC, wildmatthieu commented
il faut boooooocoup plus découper vos US
On laisse filer pour celle la, mais faites attention pour la suite

2024-06-06 15:16 UTC, wildmatthieu requested changes

2024-06-06 15:16 UTC, wildmatthieu commented on client/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
- sauvegardez les ressources en local et chargez le ensuite depuis le local
- à appliquer sur le reste du fichier

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/avengers.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/double_dragon.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/pong.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/space_invaders.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/super_sidekicks.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:16 UTC, wildmatthieu commented on client/public/image_back/x_men.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:18 UTC, wildmatthieu commented on client/src/components/CarrousselGames/CarrousselGames.jsx
l'US ne mentionne pas de carousel => est-ce vraiment à embarquer du coup ?

2024-06-06 15:19 UTC, wildmatthieu commented on client/src/components/CarrousselGames/CarrousselGames.module.css
l'US ne mentionne pas de carousel => est-ce vraiment à embarquer du coup ?

2024-06-06 15:20 UTC, wildmatthieu commented on client/src/components/Footer/Footer.jsx
l'US ne mentionne pas le footer => est-ce vraiment à embarquer du coup ?

2024-06-06 15:21 UTC, wildmatthieu commented on client/src/components/Footer/Footer.module.css
l'US ne mentionne pas le footer => est-ce vraiment à embarquer du coup ?

2024-06-06 15:21 UTC, wildmatthieu commented on client/src/components/Header/Header.jsx
l'US ne mentionne pas le header => est-ce vraiment à embarquer du coup ?

2024-06-06 15:21 UTC, wildmatthieu commented on client/src/components/Header/Header.module.css
l'US ne mentionne pas le header => est-ce vraiment à embarquer du coup ?

2024-06-06 15:22 UTC, wildmatthieu commented on client/src/main.jsx
> +    loader: async () => fetch("http://localhost:3310/api/games")
récupérer le http://localhost:3310 dans le .env situé dans le dossier client

2024-06-06 15:23 UTC, wildmatthieu commented on client/src/pages/MainPage/MainPage.jsx
> +     <CarrousselGames  games={games}/>
un espace en trop entre CarrousselGames et games

2024-06-06 15:23 UTC, wildmatthieu commented on server/app/config.js
>        "http://mysite.com",
"http://mysite.com" inutile => à retirer
De meme pour http://another-...

2024-06-06 15:24 UTC, wildmatthieu commented on server/app/config.js
> +app.use(express.json());
inutile pour le moment, à recommenter

2024-06-06 15:25 UTC, wildmatthieu commented on server/app/controllers/gameActions.js
> +  if (game != null) {
!== à la place de !=

2024-06-06 15:27 UTC, wildmatthieu commented on server/public/assets/image_back/avengers.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:27 UTC, wildmatthieu commented on server/public/assets/image_back/double_dragon.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:28 UTC, wildmatthieu commented on server/public/assets/image_back/pong.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:28 UTC, wildmatthieu commented on server/public/assets/image_back/space_invaders.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:28 UTC, wildmatthieu commented on server/public/assets/image_back/super_sidekicks.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:28 UTC, wildmatthieu commented on server/public/assets/image_back/x_men.jpg
non présent dans la maquette liée à l'US : à retirer ?

2024-06-06 15:30 UTC, wildmatthieu requested changes
beaucoup de boulot : 
- mais US bien trop grosse et à expliciter beaucoup plus/mieux

2024-06-06 16:55 UTC, MaxAnxxi commented on client/public/image_back/avengers.jpg
La maquette était simulées avec ce qui était affiché à l'écran , sur le rendu nous avons toutes les entrées provenant de la database !

2024-06-06 16:56 UTC, MaxAnxxi commented on client/src/components/CarrousselGames/CarrousselGames.jsx
Le composant a été nommé ainsi puisque dans le futur il deviendra un caroussel

2024-06-06 16:56 UTC, MaxAnxxi commented on client/src/components/Footer/Footer.jsx
La maquette correspondante a un header et un footer

2024-06-06 16:56 UTC, MaxAnxxi commented on client/src/components/Header/Header.jsx
Même commentaire qu'au dessus

2024-06-06 16:57 UTC, MaxAnxxi commented on server/app/config.js
> +app.use(express.json());
C'était sur les conseils de Marco durant le fil rouge

2024-06-07 07:40 UTC, MaxAnxxi commented
Les commentaires résolut sont fixes !

2024-06-07 08:06 UTC, merged