US05_React_Routes
WildCodeSchool-2024-02/JS-lyon-0224-P3-wildygamy pull request #33
Opened 2024-06-19 20:12 UTC by MaxAnxxi

Having the link in the header to go to the right place

2024-06-19 20:13 UTC, Salma-D38 approved these changes
good job

2024-06-20 08:03 UTC, HazeFury commented on client/src/pages/HomePage/HomePage.jsx
>        <p className={styles.connect}>Se connecter</p>
Pourquoi mettre une balise p dans un Link ?

Mettre un bouton dans un Link c'est ok mais le p n'à pas d'intérêt ici. Préférez mettre le texte dans la balise Link 😉

2024-06-20 08:04 UTC, HazeFury requested changes
Une petite modif à faire ^^

2024-06-20 08:09 UTC, MaxAnxxi commented on client/src/pages/HomePage/HomePage.jsx
>        <p className={styles.connect}>Se connecter</p>
Je suis juste aller trop vite !

2024-06-20 08:11 UTC, HazeFury approved these changes
Good 👍

2024-06-20 08:11 UTC, merged